[2025-05-16T09:11:55.534+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: breweries_etl_pipeline.transform_to_silver manual__2025-05-16T09:04:46.437449+00:00 [queued]>
[2025-05-16T09:11:55.540+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: breweries_etl_pipeline.transform_to_silver manual__2025-05-16T09:04:46.437449+00:00 [queued]>
[2025-05-16T09:11:55.542+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2025-05-16T09:11:55.549+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform_to_silver> on 2025-05-16 09:04:46.437449+00:00
[2025-05-16T09:11:55.558+0000] {standard_task_runner.py:60} INFO - Started process 90 to run task
[2025-05-16T09:11:55.565+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'breweries_etl_pipeline', 'transform_to_silver', 'manual__2025-05-16T09:04:46.437449+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/breweries_pipeline.py', '--cfg-path', '/tmp/tmp3963m2xy']
[2025-05-16T09:11:55.567+0000] {standard_task_runner.py:88} INFO - Job 17: Subtask transform_to_silver
[2025-05-16T09:11:55.580+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-05-16T09:11:55.620+0000] {task_command.py:423} INFO - Running <TaskInstance: breweries_etl_pipeline.transform_to_silver manual__2025-05-16T09:04:46.437449+00:00 [running]> on host 9264811a0e0a
[2025-05-16T09:11:55.668+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='breweries_etl_pipeline' AIRFLOW_CTX_TASK_ID='transform_to_silver' AIRFLOW_CTX_EXECUTION_DATE='2025-05-16T09:04:46.437449+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-16T09:04:46.437449+00:00'
[2025-05-16T09:11:55.671+0000] {logging_mixin.py:188} INFO - üîπ Iniciando transforma√ß√£o dos dados (Bronze ‚ûù Silver)
[2025-05-16T09:11:55.786+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/transform.py", line 21, in transform_to_silver
    spark = create_spark_session("TransformSilver")
  File "/opt/airflow/dags/src/spark_utils.py", line 12, in create_spark_session
    return SparkSession.builder \
  File "/home/airflow/.local/lib/python3.8/site-packages/pyspark/sql/session.py", line 269, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
  File "/home/airflow/.local/lib/python3.8/site-packages/pyspark/context.py", line 483, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.8/site-packages/pyspark/context.py", line 195, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.8/site-packages/pyspark/context.py", line 417, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "/home/airflow/.local/lib/python3.8/site-packages/pyspark/java_gateway.py", line 106, in launch_gateway
    raise RuntimeError("Java gateway process exited before sending its port number")
RuntimeError: Java gateway process exited before sending its port number
[2025-05-16T09:11:55.793+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=breweries_etl_pipeline, task_id=transform_to_silver, execution_date=20250516T090446, start_date=20250516T091155, end_date=20250516T091155
[2025-05-16T09:11:55.807+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 17 for task transform_to_silver (Java gateway process exited before sending its port number; 90)
[2025-05-16T09:11:55.826+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-16T09:11:55.851+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
